apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patchesJson6902:
- target:
    version: v1
    kind: Pod
    name: nginx-pod  # Original name
  patch: |-
    - op: replace
      path: /metadata/name
      value: my-custom-nginx-pod



namespace: default
