apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  releaseName: postgresql
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "13.2.25"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: postgres
      password: changeme
      database: appdb
    primary:
      persistence:
        enabled: true
        size: 8Gi
